$ANSIBLE_VAULT;1.1;AES256
35373831326139613137343037313064633664396135313164646164623339373930343034376535
3236376231626532306564303362373536643162643666310a646339363033373463396637383839
39616564366161343665623831653666613237376330363131333765346131363864386430306363
3064393161376131300a356466313866383232656335333163656265633761386461303832646265
39306536303333393835373663666161313238346565323032373662353035623266633565653237
39643564643838656665363732366239353065343832646162653039623833326663353065613934
31383739343432323065666363363530313264326433393935633166336134333666643239333863
33646237626633366561613535333866323233616263306139356665336632373064313034623639
36306161313939303661316361363261313865383461633231623430633230336430386534393230
66393436656437633439336539376336643832626363396539326531316531333130396432343834
35633366353338373238613039626461333830396631376466613761653035396563623834393363
37613563646534366239346535613633303231353062646635336431336230356332363536636165
3065
