---
- name: Create a user on all servers
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: User creation
      user:
        name: Anu
        password: intelliqit
        uid: 8899
        home: /tmp/Anu
        shell: /bin/bash
        comment: "a normal user"



...
